# To edit maps for the Portal Engine effect,
# put a Duke Nukem 3D level editor here.
# I used Mapster 0.39 Beta:
# DOS4GW.EXE
# LOOKUP.DAT
# MAPSTER.EXE
# SETUP.DAT
# TABLES.DAT
# Original Build should be also fine, see duke/level.mak.

.PHONY: clean
clean:
	$(RM) auto*.map palette.dat tiles000.art
